version: '3'
services:
  rate-limiter:
    container_name: rate-limiter
    image: ratelimiter:0.0.1
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
